---
title: "MDA-Milestone-1"
output: github_document
---

# Task 1
### Task 1.1
1. cancer_sample
2. parking_meters
3. steam_games
4. vancouver_trees

### Task 1.2
`````{r}
#Exploring datasets of interest. For each dataset, the below code provides class type, number of rows, number of columns, variable names, and provides information on how data is provided (ie. numeric or characters)

#cancer_sample
class(cancer_sample)
glimpse(cancer_sample)

#parking_meters
class(parking_meters)
glimpse(parking_meters)

#steam_games
class(steam_games)
glimpse(steam_games)

#vancouver_trees
class(vancouver_trees)
glimpse(vancouver_trees)
`````

### Task 1.3
1. cancer_sample
2. steam_games

I selected these two datasets because they contain many variables that I believe could be used to figure out some interesting information. They both provide a relatively large number of variables, so many different graphs can be made to visualize potential relations or trends. For example, when looking at the cancer_sample dataset, it would be interesting to see if there are any correlations between different traits of the tumor (ie.mean tumor compactness and mean tumor area). This could be done by creating a scatter plot and adding a trendline. In terms of the steam_games dataset, it could be interesting to see if the genre of a game is related to the sale price, or if theres any relationship between genre and mature content. 

### Task 1.4
The research question I would ask for the cancer_sample dataset would be - Are there any correlations that can be found between the different traits of a tumor, and do these traits relate to the diagnosis. 

The research question I would ask for the steam_games dataset would be - Are there any correlations between the maturity rating and genre?

I choose to work with the cancer_sample dataset for the remainder of this milestone

# Task 2
### Task 2.1
### Task 2.2

# Task 3
